version: 2
updates:
  # Actualizaciones para las dependencias de Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "golang.org/x/*"
          - "github.com/gin-gonic/*"

  # Actualizaciones para la imagen base en el Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Actualizaciones para GitHub Actions (si llegas a usarlas)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
