root = "."
tmp_dir = "tmp"

[build]
  # Solo compila archivos .go, ignora el resto para ahorrar RAM
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", ".git"]
  delay = 1000 # Espera 1 segundo tras guardar para no saturar el disco duro
  stop_on_error = true

[log]
  time = true